"""When can specific structure be recovered from under a dominant shared mode?

A controlled generator + recovery harness for the separability phase diagram.

The synthetic response matrix is

    D = sqrt(rho) * M_unit  +  sqrt(1 - rho) * [ sqrt(snr/(snr+1)) * Dspec_unit
                                                + sqrt(1/(snr+1)) * E_unit ]

where (all rescaled to unit Frobenius norm):
  * ``Dspec`` is the *known* specific structure: the total response generated by a
    sparse direct operator ``W`` via ``propagation_forward`` (the exp-23 model
    D = (I - W)^{-1} - I). Its off-diagonal nonzeros are the truth to recover.
  * ``M = outer(a, m)`` is a rank-1 *dominant shared mode* (the convergent program
    every perturbation partly engages, e.g. RPE1's cell-cycle axis).
  * ``E`` is i.i.d. Gaussian noise.

Two knobs control the regime:
  * ``rho`` in [0, 1): the dominant-mode variance fraction (RPE1's measured top-1
    SVD fraction is ~0.53).
  * ``snr`` > 0: the specific-vs-noise ratio inside the non-dominant part.

A recovery method tries to rank the off-diagonal entries so the true ``W`` edges
come out on top; recovery is scored by AUPR (and a chance-normalized version).
Sweeping (rho, snr) maps the boundary between recoverable and unrecoverable
regimes. The point: RPE1 sits at high rho with low specific-SNR, the corner where
deflation does not isolate clean structure -- exactly what experiments 21-27 found.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

from ..data.interventional import (
    deconvolve_response,
    direct_effect_filter,
    make_sparse_dag,
    propagation_forward,
    response_low_rank,
    shared_response_program,
)

RECOVERY_METHODS = ("raw", "deflate1", "program", "deconv")


@dataclass
class SeparableSystem:
    """A synthetic response matrix with known specific structure under a dominant mode."""

    response: np.ndarray  # D, n_genes x n_genes
    true_W: np.ndarray  # the known specific operator (truth lives only here)
    rho_target: float  # requested dominant-mode variance fraction
    realized_rho: float  # measured top-1 SVD variance fraction of D
    snr: float
    entanglement: float  # how much the dominant mode overlaps the specific structure
    n_genes: int
    density: float
    seed: int

    @property
    def true_edge_mask(self) -> np.ndarray:
        """Boolean off-diagonal mask of true specific edges (|W| > 0)."""
        mask = self.true_W != 0.0
        np.fill_diagonal(mask, False)
        return mask

    @property
    def true_edge_density(self) -> float:
        """Fraction of off-diagonal entries that are true edges (the AUPR chance line)."""
        n = self.n_genes
        off = n * (n - 1)
        return float(self.true_edge_mask.sum()) / off if off else float("nan")


def _unit_frobenius(matrix: np.ndarray) -> np.ndarray:
    """Rescale a matrix to unit Frobenius norm (no-op for an all-zero matrix)."""
    norm = float(np.linalg.norm(matrix))
    return matrix / norm if norm > 0 else matrix


def _unit_vector(vector: np.ndarray) -> np.ndarray:
    """Rescale a vector to unit L2 norm (no-op for an all-zero vector)."""
    norm = float(np.linalg.norm(vector))
    return vector / norm if norm > 0 else vector


def make_separable_system(
    *,
    n_genes: int = 60,
    density: float = 0.05,
    rho: float = 0.5,
    snr: float = 1.0,
    entanglement: float = 0.0,
    seed: int = 0,
) -> SeparableSystem:
    """Generate a response matrix mixing a known specific operator, a dominant rank-1
    shared mode, and noise.

    Knobs:
      * ``rho`` in [0, 1): dominant-mode variance fraction.
      * ``snr`` > 0: specific-vs-noise ratio inside the non-dominant part.
      * ``entanglement`` in [0, 1]: how much the dominant mode aligns with the specific
        structure's principal direction. At 0 the mode is orthogonal random (deflation
        removes it cleanly); at 1 the mode IS the specific structure's top component, so
        removing it also destroys the most-recoverable specific signal -- the RPE1 regime
        where global-mode removal does not isolate clean structure (experiment 21).
    """
    if not 0.0 <= rho < 1.0:
        raise ValueError("rho must be in [0, 1)")
    if snr <= 0.0:
        raise ValueError("snr must be positive")
    if not 0.0 <= entanglement <= 1.0:
        raise ValueError("entanglement must be in [0, 1]")

    W = make_sparse_dag(n_genes, density, seed=seed, dag=True)
    Dspec = propagation_forward(W)  # off-diagonal total response of the specific operator
    np.fill_diagonal(Dspec, 0.0)

    # principal direction of the specific structure (its top singular vectors)
    left, _s, right = np.linalg.svd(Dspec, full_matrices=False)
    u1, v1 = left[:, 0], right[0]

    rng = np.random.default_rng(seed + 1)
    a = (1.0 - entanglement) * _unit_vector(rng.standard_normal(n_genes)) + entanglement * _unit_vector(u1)
    m = (1.0 - entanglement) * _unit_vector(rng.standard_normal(n_genes)) + entanglement * _unit_vector(v1)
    M = np.outer(a, m)
    E = rng.standard_normal((n_genes, n_genes))

    dspec_u = _unit_frobenius(Dspec)
    m_u = _unit_frobenius(M)
    e_u = _unit_frobenius(E)

    structure = np.sqrt(snr / (snr + 1.0)) * dspec_u + np.sqrt(1.0 / (snr + 1.0)) * e_u
    structure_u = _unit_frobenius(structure)

    D = np.sqrt(rho) * m_u + np.sqrt(1.0 - rho) * structure_u
    realized_rho = float(response_low_rank(pd.DataFrame(D))["top1_var"])

    return SeparableSystem(
        response=D,
        true_W=W,
        rho_target=float(rho),
        realized_rho=realized_rho,
        snr=float(snr),
        entanglement=float(entanglement),
        n_genes=n_genes,
        density=density,
        seed=seed,
    )


def recover_specific(D: np.ndarray, method: str = "raw", *, lam: float = 0.1) -> np.ndarray:
    """Return an off-diagonal score matrix ranking candidate specific edges.

    Methods:
      * ``raw``     : |D| (no attempt to remove the dominant mode).
      * ``deflate1``: |D after removing the top-1 SVD mode| (blind global-mode removal).
      * ``program`` : |residual after subtracting the shared response program| (the
        interpretable rank-1 program, ``shared_response_program``).
      * ``deconv``  : |ridge deconvolution operator W_hat| (the exp-23 linear inverse).
    """
    if method == "raw":
        score = np.abs(D)
    elif method == "deflate1":
        residual, _ = direct_effect_filter(pd.DataFrame(D), n_modes=1)
        score = np.abs(residual.to_numpy())
    elif method == "program":
        residual = shared_response_program(pd.DataFrame(D))["residual"].to_numpy()
        score = np.abs(residual)
    elif method == "deconv":
        score = np.abs(deconvolve_response(D, method="ridge", lam=lam))
    else:
        raise ValueError(f"unknown recovery method {method!r}")
    score = score.copy()
    np.fill_diagonal(score, 0.0)
    return score


def specific_recovery_aupr(score: np.ndarray, true_W: np.ndarray) -> float:
    """AUPR of an off-diagonal score matrix against the true specific-edge mask."""
    from sklearn.metrics import average_precision_score

    n = true_W.shape[0]
    off = ~np.eye(n, dtype=bool)
    y_true = (true_W[off] != 0.0).astype(int)
    y_score = score[off].astype(float)
    if y_true.sum() == 0 or y_true.sum() == y_true.size:
        return float("nan")
    return float(average_precision_score(y_true, y_score))


def normalized_recovery(aupr: float, chance: float) -> float:
    """Chance-normalized recovery in (-inf, 1]: (AUPR - chance) / (1 - chance).

    0 = no better than the edge-density prior; 1 = perfect; <0 = worse than chance.
    """
    if not np.isfinite(aupr) or not np.isfinite(chance) or chance >= 1.0:
        return float("nan")
    return float((aupr - chance) / (1.0 - chance))


def separability_grid(
    rho_values,
    entanglement_values,
    *,
    snr_values=(1.0,),
    n_genes: int = 60,
    density: float = 0.05,
    methods=RECOVERY_METHODS,
    n_seeds: int = 3,
    base_seed: int = 0,
) -> pd.DataFrame:
    """Sweep (rho, entanglement, snr) over seeds and recovery methods; tidy results frame.

    Columns: rho, entanglement, snr, method, n_genes, density, realized_rho,
    true_edge_density, aupr (mean over seeds), aupr_std, normalized_recovery, n_seeds.
    """
    rows: list[dict[str, object]] = []
    for rho in rho_values:
        for ent in entanglement_values:
            for snr in snr_values:
                systems = [
                    make_separable_system(
                        n_genes=n_genes, density=density, rho=float(rho), snr=float(snr),
                        entanglement=float(ent), seed=base_seed + s,
                    )
                    for s in range(n_seeds)
                ]
                chance = float(np.mean([sys.true_edge_density for sys in systems]))
                realized = float(np.mean([sys.realized_rho for sys in systems]))
                for method in methods:
                    auprs = [
                        specific_recovery_aupr(recover_specific(sys.response, method), sys.true_W)
                        for sys in systems
                    ]
                    auprs = [a for a in auprs if np.isfinite(a)]
                    mean_aupr = float(np.mean(auprs)) if auprs else float("nan")
                    rows.append(
                        {
                            "rho": float(rho),
                            "entanglement": float(ent),
                            "snr": float(snr),
                            "method": method,
                            "n_genes": n_genes,
                            "density": density,
                            "realized_rho": realized,
                            "true_edge_density": chance,
                            "aupr": mean_aupr,
                            "aupr_std": float(np.std(auprs)) if len(auprs) > 1 else 0.0,
                            "normalized_recovery": normalized_recovery(mean_aupr, chance),
                            "n_seeds": len(auprs),
                        }
                    )
    return pd.DataFrame(rows)


def recoverability_boundary(
    grid: pd.DataFrame, *, threshold: float = 0.2, by=("entanglement", "snr"), axis: str = "rho"
) -> pd.DataFrame:
    """For each (method, *by*) slice, the largest ``axis`` value whose normalized recovery
    still exceeds ``threshold`` -- the recoverability boundary. NaN if never above."""
    by = [by] if isinstance(by, str) else list(by)
    by = [c for c in by if c in grid.columns]
    rows: list[dict[str, object]] = []
    for key, block in grid.groupby(["method", *by]):
        method, slice_keys = key[0], key[1:]
        ok = block[block["normalized_recovery"] > threshold]
        boundary = float(ok[axis].max()) if len(ok) else float("nan")
        row = {"method": method}
        for col, val in zip(by, slice_keys):
            row[col] = val
        row["threshold"] = threshold
        row[f"max_recoverable_{axis}"] = boundary
        row["best_normalized_recovery"] = float(block["normalized_recovery"].max())
        rows.append(row)
    return pd.DataFrame(rows).sort_values(["method", *by]).reset_index(drop=True)
