from collections.abc import Callable, Sequence
import itertools

import numpy as np
import pandas as pd

Ranker = Callable[[pd.DataFrame], pd.DataFrame]


def edge_selection_frequencies(edge_tables: list[pd.DataFrame]) -> pd.DataFrame:
    """Summarize how often each edge appears across repeated inference runs.

    Parameters
    ----------
    edge_tables:
        List of edge tables. Each table must contain ``source`` and ``target``
        columns for selected edges from one bootstrap or subsampling run.

    Returns
    -------
    pandas.DataFrame
        Edge table with ``source``, ``target``, and ``frequency`` columns.

    """
    if not edge_tables:
        return pd.DataFrame(columns=["source", "target", "frequency"])

    counts: dict[tuple[str, str], int] = {}
    for table in edge_tables:
        for row in table[["source", "target"]].drop_duplicates().itertuples(index=False):
            edge = (str(row.source), str(row.target))
            counts[edge] = counts.get(edge, 0) + 1

    total_runs = len(edge_tables)
    rows = [
        {"source": source, "target": target, "frequency": count / total_runs}
        for (source, target), count in counts.items()
    ]
    return pd.DataFrame(rows).sort_values("frequency", ascending=False).reset_index(drop=True)


def directed_nonself_edges(genes: Sequence[str]) -> pd.DataFrame:
    """Return all directed non-self edges for an ordered gene list."""
    rows = [
        {"source": str(source), "target": str(target)}
        for source, target in itertools.permutations(genes, 2)
    ]
    return pd.DataFrame(rows)


def generate_resample_indices(
    n_samples: int,
    n_resamples: int,
    *,
    method: str = "bootstrap",
    sample_fraction: float = 0.8,
    random_seed: int = 0,
) -> list[np.ndarray]:
    """Generate reproducible bootstrap or subsampling row indices.

    Parameters
    ----------
    n_samples:
        Number of rows in the original dataset.
    n_resamples:
        Number of resampled datasets to generate.
    method:
        Either ``"bootstrap"`` for sampling with replacement or
        ``"subsample"`` for sampling without replacement.
    sample_fraction:
        Fraction of rows to use for subsampling. Ignored for bootstrap, where
        each resample has ``n_samples`` rows.
    random_seed:
        Seed for reproducible index generation.

    Returns
    -------
    list[numpy.ndarray]
        One integer index array per resample.
    """
    if n_samples <= 0:
        raise ValueError("n_samples must be positive")
    if n_resamples <= 0:
        raise ValueError("n_resamples must be positive")
    if not 0 < sample_fraction <= 1:
        raise ValueError("sample_fraction must be in (0, 1]")

    rng = np.random.default_rng(random_seed)
    if method == "bootstrap":
        return [rng.integers(0, n_samples, size=n_samples) for _ in range(n_resamples)]
    if method == "subsample":
        sample_size = max(1, int(round(n_samples * sample_fraction)))
        return [
            rng.choice(n_samples, size=sample_size, replace=False)
            for _ in range(n_resamples)
        ]
    raise ValueError("method must be 'bootstrap' or 'subsample'")


def summarize_resampled_edge_scores(
    expression: pd.DataFrame,
    ranker: Ranker,
    resample_indices: list[np.ndarray],
    *,
    top_k: int = 20,
    selection_threshold: float = 0.0,
) -> pd.DataFrame:
    """Summarize edge scores across resampled expression matrices.

    Parameters
    ----------
    expression:
        Original expression matrix with genes in columns.
    ranker:
        Function that accepts an expression matrix and returns ``source``,
        ``target``, and ``score`` columns for directed non-self edges.
    resample_indices:
        Row-index arrays generated by ``generate_resample_indices``.
    top_k:
        Rank cutoff used for top-k selection frequency.
    selection_threshold:
        Score threshold used for selection frequency. For sparse coefficient
        methods, a threshold of zero means "selected if coefficient magnitude is
        nonzero."

    Returns
    -------
    pandas.DataFrame
        One row per directed non-self edge, with mean score, mean reciprocal
        rank, top-k frequency, and selection frequency across resamples.
    """
    if top_k <= 0:
        raise ValueError("top_k must be positive")
    if not resample_indices:
        raise ValueError("resample_indices must not be empty")

    edges = directed_nonself_edges(list(expression.columns))
    n_edges = len(edges)
    score_sum = np.zeros(n_edges, dtype=float)
    reciprocal_rank_sum = np.zeros(n_edges, dtype=float)
    top_k_count = np.zeros(n_edges, dtype=float)
    selected_count = np.zeros(n_edges, dtype=float)

    for indices in resample_indices:
        sample = expression.iloc[indices].reset_index(drop=True)
        ranked = ranker(sample)[["source", "target", "score"]].copy()
        ranked["rank"] = np.arange(1, len(ranked) + 1)

        merged = edges.merge(ranked, on=["source", "target"], how="left")
        merged["score"] = merged["score"].fillna(0.0)
        merged["rank"] = merged["rank"].fillna(n_edges + 1)

        scores = merged["score"].to_numpy(dtype=float)
        ranks = merged["rank"].to_numpy(dtype=float)
        score_sum += scores
        reciprocal_rank_sum += 1.0 / ranks
        top_k_count += ranks <= top_k
        selected_count += scores > selection_threshold

    n_resamples = len(resample_indices)
    result = edges.copy()
    result["mean_score"] = score_sum / n_resamples
    result["mean_reciprocal_rank"] = reciprocal_rank_sum / n_resamples
    result["top_k_frequency"] = top_k_count / n_resamples
    result["selection_frequency"] = selected_count / n_resamples
    return result
